name: Samuel Crees
favicon: null
layout_spectrum: 0.67735
typography_spectrum: 0.34203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#068edc'
    - '#ffffff'
    - '#c3a88d'
    - '#12232a'
    - '#6c6447'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.2112876633182168
  rhythmicContrast: 0
purpose: []
